#!/bin/bash

if [ ! $# == 0 ]; then
    MAJOR=$1
    MINOR=$2
    PATCH=$3
    # set default minor
    if [ -e $MINOR ]; then
        MINOR=0
    fi
    # set default patch
    if [ -e $PATCH ]; then
            PATCH=0
    fi
    VN=$((($MAJOR*1000000)+($MINOR*1000)+($PATCH-1)))
fi

if [ $# == 0 ]; then
    VN=`grep -o '#define PHP_CAN_VN [[:digit:]]\{1,\}' version.h|tr -d '#define PHP_CAN_VN \n'`
fi

# Bump the number
VN=$(($VN + 1))
RELEASE="$(($VN/1000000)).$(( ($VN/1000)%1000 )).$(( $VN%1000 ))"
echo "Bumping sources to release $RELEASE ($VN)"
# wright to version.h
echo "// DO NOT EDIT ! THIS FILE IS AUTOGENERATED!!!" > version.h
echo "#define PHP_CAN_VN ${VN}" >> version.h
echo "#define PHP_CAN_VERSION \"${RELEASE}\"" >> version.h
